### ISSUE TITLE
Deprecated SciPy function import

### ISSUE THREAD

**Issue by mrileyowens** [jkrogager/VoigtFit#61]
VoigtFit imports `scipy.signal.gaussian` in `voigt.py`, but `scipy.signal.gaussian` appears to be deprecated and I think since replaced by `scipy.signal.windows.gaussian`. But VoigtFit does not specify in `requirements.txt` that a specific version of SciPy is necessary. Presently, `scipy==1.13.0` and `VoigtFit==3.21.4` leads to the following error for me:

`ImportError: cannot import name 'gaussian' from 'scipy.signal'`

Can the required version of SciPy be specified in `requirements.txt`, and can the code be changed to support the newer version of SciPy?

**Comment by jkrogager** [comment]
Could you please tell me which version of Python and SciPy you're using? I don't get a deprecation warning on my end (in Python 3.11). I'll run some tests to make sure that nothing else breaks when updating SciPy. I seem to remember that it was a conflict with Numba, which has since been removed. I'll let you know.

**Comment by mrileyowens** [comment]
I am using Python 3.12.2 and SciPy 1.13.0.

**Comment by jkrogager** [comment]
Hi again, sorry for the wait. I just pushed a fix (pull request #62). It worked on my local environments with both scipy 1.10 and 1.13. Let me know if it didn't work for you. Closing the issue for now

**Comment by mrileyowens** [comment]
@jkrogager there is still an instance of the deprecated import on line 11 of output.py that still leads to the original ImportError for me (after updating VoigtFit to 3.21.5 with SciPy 1.13 and Python 3.12.2). Apologies I didn't mention the specific location when opening the issue. Line 5 of make_synthetic_data.py also uses the same deprecated import.

**Comment by jkrogager** [comment]
Ahhh sorry about that. Slipped through the cracks. Should be fixed now.
